/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfopus;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author cosnors
 */
public class FormMenuUtamaPustakawan extends javax.swing.JFrame {
    KoneksiDB kon = new KoneksiDB();
    public Date date = new Date();
    public SimpleDateFormat noformat = new SimpleDateFormat("dd-MM-yyyy");
    public String KodePegawai;
    public String Level;
    public String NamaPegawai;
    /**
     * Creates new form FormMenuUtama
     */
    public FormMenuUtamaPustakawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llevel = new javax.swing.JLabel();
        lnama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lkode = new javax.swing.JLabel();
        ltanggal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnKeluar = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        mnTransaksiPeminjaman = new javax.swing.JMenuItem();
        mnTransaksiPengembalian = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnLaporanBuku = new javax.swing.JMenuItem();
        mnLaporanTransaksiPeminjaman = new javax.swing.JMenuItem();
        mnLaporanTransaksiPengembalian = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnPengaturanJumlahDenda = new javax.swing.JMenuItem();
        mnPengaturanPassword = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        llevel.setText("-");

        lnama.setText("-");

        jLabel1.setText("Selamat Datang di Sisfopus, ");

        jLabel2.setText("Kode Pegawai Anda  :");

        jLabel3.setText("Akses Level Anda    :");

        lkode.setText("-");

        ltanggal.setText("-");

        mnFile.setText("File");

        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        mnFile.add(mnKeluar);

        jMenuBar1.add(mnFile);

        mnTransaksi.setText("Transaksi");

        mnTransaksiPeminjaman.setText("Transaksi Peminjaman");
        mnTransaksiPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiPeminjamanActionPerformed(evt);
            }
        });
        mnTransaksi.add(mnTransaksiPeminjaman);

        mnTransaksiPengembalian.setText("Transaksi Pengembalian");
        mnTransaksiPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiPengembalianActionPerformed(evt);
            }
        });
        mnTransaksi.add(mnTransaksiPengembalian);

        jMenuBar1.add(mnTransaksi);

        jMenu4.setText("Laporan");

        mnLaporanBuku.setText("Data Buku");
        mnLaporanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanBukuActionPerformed(evt);
            }
        });
        jMenu4.add(mnLaporanBuku);

        mnLaporanTransaksiPeminjaman.setText("Data Transaksi Peminjaman");
        mnLaporanTransaksiPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanTransaksiPeminjamanActionPerformed(evt);
            }
        });
        jMenu4.add(mnLaporanTransaksiPeminjaman);

        mnLaporanTransaksiPengembalian.setText("Data Transaksi Pengembalian");
        mnLaporanTransaksiPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanTransaksiPengembalianActionPerformed(evt);
            }
        });
        jMenu4.add(mnLaporanTransaksiPengembalian);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Pengaturan");

        mnPengaturanJumlahDenda.setText("Pengaturan Denda");
        mnPengaturanJumlahDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPengaturanJumlahDendaActionPerformed(evt);
            }
        });
        jMenu5.add(mnPengaturanJumlahDenda);

        mnPengaturanPassword.setText("Pengaturan Password");
        mnPengaturanPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPengaturanPasswordActionPerformed(evt);
            }
        });
        jMenu5.add(mnPengaturanPassword);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 743, Short.MAX_VALUE)
                        .addComponent(ltanggal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lkode)
                            .addComponent(llevel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ltanggal)
                    .addComponent(lnama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lkode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(llevel))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnLaporanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanBukuActionPerformed
        // TODO add your handling code here:
        try {
            String path = "src/sisfopus/LaporanBuku.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mnLaporanBukuActionPerformed

    private void mnTransaksiPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiPeminjamanActionPerformed
        // TODO add your handling code here:
        FormTransaksiPeminjaman transaksiPeminjaman = new FormTransaksiPeminjaman();
        transaksiPeminjaman.setLocationRelativeTo(null);
        transaksiPeminjaman.setVisible(true);
    }//GEN-LAST:event_mnTransaksiPeminjamanActionPerformed

    private void mnTransaksiPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiPengembalianActionPerformed
        // TODO add your handling code here:
        FormTransaksiPengembalian transaksiPengembalian = new FormTransaksiPengembalian();
        transaksiPengembalian.setLocationRelativeTo(null);
        transaksiPengembalian.setVisible(true);
    }//GEN-LAST:event_mnTransaksiPengembalianActionPerformed

    private void mnPengaturanPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPengaturanPasswordActionPerformed
        // TODO add your handling code here:
        FormPengaturanPassword pengaturanPassword = new FormPengaturanPassword();
        pengaturanPassword.setLocationRelativeTo(null);
        pengaturanPassword.setVisible(true);
        pengaturanPassword.KodePegawai=lkode.getText();
    }//GEN-LAST:event_mnPengaturanPasswordActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lnama.setText(NamaPegawai);
        lkode.setText(KodePegawai);
        ltanggal.setText(noformat.format(date));
        llevel.setText(Level);
    }//GEN-LAST:event_formWindowActivated

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnLaporanTransaksiPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanTransaksiPeminjamanActionPerformed
        // TODO add your handling code here:
//        FormLaporanPeminjamanPengembalian peminjamanpengembalian = new FormLaporanPeminjamanPengembalian();
//        peminjamanpengembalian.setLocationRelativeTo(null);
//        peminjamanpengembalian.setVisible(true);
    try {
            String path = "src/sisfopus/LaporanTransaksiPeminjaman.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mnLaporanTransaksiPeminjamanActionPerformed

    private void mnPengaturanJumlahDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPengaturanJumlahDendaActionPerformed
        // TODO add your handling code here:
        FormPengaturanDenda pengaturanDenda = new FormPengaturanDenda();
        pengaturanDenda.setLocationRelativeTo(null);
        pengaturanDenda.setVisible(true);
    }//GEN-LAST:event_mnPengaturanJumlahDendaActionPerformed

    private void mnLaporanTransaksiPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanTransaksiPengembalianActionPerformed
        // TODO add your handling code here:
        try {
            String path = "src/sisfopus/LaporanPengembalian.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mnLaporanTransaksiPengembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtamaPustakawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtamaPustakawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtamaPustakawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtamaPustakawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuUtamaPustakawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lkode;
    private javax.swing.JLabel llevel;
    private javax.swing.JLabel lnama;
    private javax.swing.JLabel ltanggal;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnLaporanBuku;
    private javax.swing.JMenuItem mnLaporanTransaksiPeminjaman;
    private javax.swing.JMenuItem mnLaporanTransaksiPengembalian;
    private javax.swing.JMenuItem mnPengaturanJumlahDenda;
    private javax.swing.JMenuItem mnPengaturanPassword;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JMenuItem mnTransaksiPeminjaman;
    private javax.swing.JMenuItem mnTransaksiPengembalian;
    // End of variables declaration//GEN-END:variables
}
